// Angular2/tiendaAngular/src/app/producto/producto.component.ts
import { Component, OnInit } from '@angular/core';
import {ActivatedRoute} from "@angular/router";

import { AppComponent } from '../app.component'

@Component({
  selector: 'app-producto',
  templateUrl: './producto.component.html',
  styleUrls: ['./producto.component.css']
})
export class ProductoComponent implements OnInit {

  public nombreProducto: string;
  public imageProducto: string;
  public cantidadProducto: string;
  public precioProducto: string;

  constructor(private route: ActivatedRoute, public appComponent : AppComponent) {
    this.route.queryParams.subscribe(params => {
          this.nombreProducto = params["nombreProducto"];
          this.imageProducto = params["imagenProducto"];
          this.cantidadProducto = params["unidadesProducto"];
          this.precioProducto = params["precioProducto"];
      });
  }

  ngOnInit() {
    this.appComponent.changeValue();
  }

}

<div class="container productoContainer" style="padding-bottom:50px;">
  <div class="row">
    <div class="col s12">
      <h3>{{nombreProducto}}</h3>
    </div>
    <div class="col s6">
      <img src="{{imageProducto}}">
      <a [routerLink]="['/tienda']" class="waves-effect grey lighten-3 btn">Atras</a>
    </div>
    <div class="col s6">
      <div class="chip">
        <strong>Precio: </strong> {{precioProducto}}
      </div>
      <br>
      <div class="chip">
        <strong>Unidades Disponibles: </strong> {{cantidadProducto}}
      </div>
    </div>
  </div>
</div>

// React/components/tienda/Producto.jsx
import React from 'react';
import { Link } from 'react-router-dom'

class Producto extends React.Component{

  constructor(props){
    super(props)
    this.state = {

      }
    }

    render() {

    console.log(this.props.match.params);

        return(
        <div className="container productoContainer">
          <div className="row">
            <div className="col s12">
              <h3>{this.props.match.params.nombre}</h3>
            </div>
            <div className="col s6">
              <img src={"/assets/productos/" + this.props.match.params.nombre + ".jpg "}/>
              <Link to={`/tienda`} className="waves-effect grey lighten-3 btn">Atras</Link>
            </div>
            <div className="col s6">
              <div className="chip">
                <strong>Precio: </strong> {this.props.match.params.precio}
              </div>
              <br/>
              <div className="chip">
                <strong>Unidades Disponibles: </strong> {this.props.match.params.cantidad}
              </div>
            </div>
          </div>
        </div>
        )
    }


}
export default Producto;
